services:
  - type: web
    name: mental-pasienter-backend
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python -m flask --app manage.py db upgrade heads
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: APP_DEBUG_LOG_PATH
        value: /opt/render/project/src/Backend/app_debug.log
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: STEAM_WEB_API_KEY
        sync: false
      - key: MAILERSEND_SERVER
        sync: false
      - key: MAILERSEND_PORT
        sync: false
      - key: MAILERSEND_USE_TLS
        sync: false
      - key: MAILERSEND_USERNAME
        sync: false
      - key: MAILERSEND_PASSWORD
        sync: false
      - key: MAILERSEND_DEFAULT_SENDER
        sync: false
      - key: SUPPORT_SERVER
        sync: false
      - key: SUPPORT_PORT
        sync: false
      - key: SUPPORT_USE_TLS
        sync: false
      - key: SUPPORT_USERNAME
        sync: false
      - key: SUPPORT_PASSWORD
        sync: false
      - key: SUPPORT_DEFAULT_SENDER
        sync: false
