"""empty message

Revision ID: 64d07b63c1c6
Revises: c6c613db3b19
Create Date: 2025-03-08 00:06:20.215736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d07b63c1c6'
down_revision = 'c6c613db3b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('template_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('template_name')
        batch_op.drop_column('event_image_path')

    # ### end Alembic commands ###
