"""Add rank field to User model

Revision ID: 7d3268e4e30a
Revises: cc59cb0d0620
Create Date: 2025-02-23 09:12:31.918664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3268e4e30a'
down_revision = 'cc59cb0d0620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
