"""Add foreign key to thread.user_id

Revision ID: 243189820679
Revises: 098c829b8000
Create Date: 2025-02-15 10:38:29.718890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243189820679'
down_revision = '098c829b8000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
