"""Added krenke_level column to User model

Revision ID: 384cbce36db7
Revises: 64d07b63c1c6
Create Date: 2025-03-12 15:21:12.639029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384cbce36db7'
down_revision = '64d07b63c1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('krenke_level', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('krenke_level')

    # ### end Alembic commands ###
