"""Add fitte_points column

Revision ID: 99452ad27038
Revises: 56aba546703b
Create Date: 2025-03-22 03:15:30.330972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99452ad27038'
down_revision = '56aba546703b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitte_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fitte_points')

    # ### end Alembic commands ###
