"""Add Setting model for maintenance mode

Revision ID: a6621a08d8c7
Revises: 7cbdb6dc05a6
Create Date: 2025-04-11 16:47:40.662445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6621a08d8c7'
down_revision = '7cbdb6dc05a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index('key')

    op.drop_table('setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)

    op.drop_table('settings')
    # ### end Alembic commands ###
