"""Added thread_id foreign key to Comment model

Revision ID: bb610dac7329
Revises: 0d815c290935
Create Date: 2025-02-13 20:15:01.748574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb610dac7329'
down_revision = '0d815c290935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
