"""Add cover and soundcloudUrl fields to Song

Revision ID: bce3aeac0f60
Revises: 99452ad27038
Create Date: 2025-04-05 13:14:20.473788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bce3aeac0f60'
down_revision = '99452ad27038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('soundcloudUrl', sa.String(length=255), nullable=True))
        batch_op.drop_index('file_path')
        batch_op.drop_column('file_path')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(length=500), nullable=False))
        batch_op.create_index('file_path', ['file_path'], unique=True)
        batch_op.drop_column('soundcloudUrl')
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
