"""Add Setting model

Revision ID: be9b0f22a00c
Revises: a6621a08d8c7
Create Date: 2025-04-11 17:06:16.879315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be9b0f22a00c'
down_revision = 'a6621a08d8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('key')

    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)

    # ### end Alembic commands ###
