"""Updated models with user relationship

Revision ID: 098c829b8000
Revises: 0a5db5e77781
Create Date: 2025-02-15 10:27:50.023503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098c829b8000'
down_revision = '0a5db5e77781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'thread', ['thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
