"""create fitte_points table

Revision ID: 125e3ef20c02
Revises: d954c4ea1cf9
Create Date: 2025-04-21 14:09:21.167737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125e3ef20c02'
down_revision = 'd954c4ea1cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitte_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fitte_points')
    # ### end Alembic commands ###
