"""Enable ondelete cascade

Revision ID: 22805c496df9
Revises: c6bee2578681
Create Date: 2025-02-16 00:14:43.133664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22805c496df9'
down_revision = 'c6bee2578681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_1', 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###
