"""Add Friend model

Revision ID: 5c0b49cc3c14
Revises: 808ba7181af0
Create Date: 2025-04-17 16:40:03.467582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c0b49cc3c14'
down_revision = '808ba7181af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_assoc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_assoc',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='friend_assoc_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='friend_assoc_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
