"""Add friend_assoc join table and User.friends relationship

Revision ID: 808ba7181af0
Revises: a434ed8a649b
Create Date: 2025-04-17 14:18:24.184697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808ba7181af0'
down_revision = 'a434ed8a649b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_assoc')
    # ### end Alembic commands ###
