"""Add TeamMember model

Revision ID: d954c4ea1cf9
Revises: dac52e86150c
Create Date: 2025-04-20 13:47:35.385106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd954c4ea1cf9'
down_revision = 'dac52e86150c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friend_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'accepted', 'declined'), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name='friend_requests_ibfk_1'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name='friend_requests_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('team_member')
    # ### end Alembic commands ###
