"""Add banner column to User model

Revision ID: fb7613634b3b
Revises: 7d3268e4e30a
Create Date: 2025-03-02 09:07:13.677776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7613634b3b'
down_revision = '7d3268e4e30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('banner')

    # ### end Alembic commands ###
